"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, CalendarClock, FileText, History, PauseCircle, Play, RefreshCw, RotateCcw, Settings2, XCircle } from "lucide-react";
import { OperationCreationDrawer } from "@platform/components/operation-creation-drawer";
import { Pagination } from "@platform/components/pagination";
import {
  ApiClientError, operationApi, pmocApi, usersApi, useQuery,
  type CreateOperationPayload, type PmocExecutionRequest, type PmocHistoryItem, type PmocPlan,
} from "@erp/api";
import { useAuth } from "@erp/ui/auth/auth-provider";
import { ConfirmDialog } from "@erp/ui/confirm-dialog";
import { Drawer } from "@erp/ui/drawer";
import { DocumentViewer } from "@erp/ui/documents/document-viewer";
import { EmptyState } from "@erp/ui/empty-state";
import { SkeletonCard, SkeletonList } from "@erp/ui/skeletons";
import { ErrorState } from "@erp/ui/states";
import { StatusChip } from "@erp/ui/status-chip";

type Tab = "summary" | "requests" | "timeline";

export default function PmocDetailPage() {
  const { id } = useParams<{ id: string }>();
  const { hasRole } = useAuth();
  const canEdit = hasRole("OWNER", "MANAGER");
  const [tab, setTab] = useState<Tab>("summary");
  const [requestPage, setRequestPage] = useState(1);
  const [requestLimit, setRequestLimit] = useState(20);
  const [tick, setTick] = useState(0);
  const pmoc = useQuery((signal) => pmocApi.getPmoc(id, { signal }), [id, tick]);
  const requests = useQuery((signal) => pmocApi.listExecutionRequests(id, { page: requestPage, limit: requestLimit, signal }), [id, requestPage, requestLimit, tick]);
  const history = useQuery<PmocHistoryItem[]>(() => pmocApi.getHistory(id), [id, tick]);
  const [generating, setGenerating] = useState<PmocExecutionRequest | null>(null);
  const [prefill, setPrefill] = useState<CreateOperationPayload | null>(null);
  const [rescheduling, setRescheduling] = useState<PmocExecutionRequest | null>(null);
  const [canceling, setCanceling] = useState<PmocExecutionRequest | null>(null);
  const [settings, setSettings] = useState(false);
  const [documentRequest, setDocumentRequest] = useState<PmocExecutionRequest | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function openGeneration(request: PmocExecutionRequest) {
    setError(null);
    try { setPrefill(await pmocApi.getExecutionRequestPrefill(request.id)); setGenerating(request); }
    catch (cause) { setError(message(cause)); }
  }
  async function submitOperation(payload: CreateOperationPayload) {
    if (!generating) throw new Error("Execução não selecionada.");
    const request = await pmocApi.generateWorkOrder(generating.id, payload);
    if (!request.operationId) throw new Error("OS não vinculada.");
    setTick((value) => value + 1);
    return operationApi.getOperation(request.operationId);
  }

  if (pmoc.loading && !pmoc.data) return <SkeletonCard />;
  if (pmoc.error && !pmoc.data) return <ErrorState error={pmoc.error} onRetry={pmoc.refetch} />;
  if (!pmoc.data) return <EmptyState icon={CalendarClock} title="PMOC não encontrado" description="O plano não está disponível." />;
  const plan = pmoc.data;
  const items = requests.data?.items ?? [];
  const overview = plan.overview;

  return <div className="space-y-6">
    <Link href="/pmoc" className="inline-flex items-center gap-2 text-sm text-[var(--color-muted-foreground)]"><ArrowLeft className="h-4 w-4" /> Voltar para PMOC</Link>
    <header className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><span className="text-xs font-semibold uppercase tracking-wide text-[var(--color-primary)]">PMOC-{String(plan.number).padStart(6, "0")}</span><StatusChip tone={overview?.health.tone ?? (plan.operationalStatus === "PAUSED" ? "warning" : "success")}>{overview?.health.label ?? operationalStatusLabel(plan.operationalStatus)}</StatusChip></div><h1 className="mt-2 text-2xl font-semibold">{plan.maintenancePlan?.name}</h1><p className="mt-1 text-sm text-[var(--color-muted-foreground)]">{plan.customer?.tradeName ?? plan.customer?.name} · {periodicityLabel(plan.periodicity)} · {generationModeLabel(plan.generationMode)}</p></div>{canEdit && <div className="flex flex-wrap gap-2"><button className={secondary} onClick={async () => { await pmocApi.updatePmoc(plan.id, { generationMode: plan.generationMode === "PAUSED" ? "MANUAL" : "PAUSED" }); setTick((value) => value + 1); }}>{plan.generationMode === "PAUSED" ? <><RotateCcw className="h-4 w-4" /> Retomar plano</> : <><PauseCircle className="h-4 w-4" /> Pausar plano</>}</button><button className={secondary} onClick={() => setSettings(true)}><Settings2 className="h-4 w-4" /> Configurar responsáveis</button></div>}</header>
    {error && <div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-700">{error}</div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Previstas" value={overview?.expectedExecutions ?? "—"} /><Metric label="Concluídas" value={overview?.completedExecutions ?? "—"} /><Metric label="Pendentes" value={overview?.pendingExecutions ?? "—"} /><Metric label="Falhas" value={overview?.failedExecutions ?? "—"} tone="danger" /><Metric label="Canceladas" value={overview?.cancelledExecutions ?? "—"} /><Metric label="Próxima" value={date(plan.nextExecutionDate)} /></div>
    {overview && <section className="rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-4"><div className="flex items-center justify-between text-sm"><strong>Progresso das execuções</strong><span>{overview.completedExecutions} / {overview.expectedExecutions} · {overview.remainingExecutions} restantes</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-[var(--color-muted)]"><div className="h-full rounded-full bg-[var(--color-primary)]" style={{ width: `${overview.completionPercentage}%` }} /></div><p className="mt-2 text-xs text-[var(--color-muted-foreground)]">Saúde {overview.health.label} ({overview.health.score}/100) · atraso médio {overview.averageDelayDays} dia(s)</p></section>}
    <nav className="flex gap-1 border-b border-[var(--color-border)]">{(["summary", "requests", "timeline"] as Tab[]).map((value) => <button key={value} className={`px-4 py-3 text-sm font-medium ${tab === value ? "border-b-2 border-[var(--color-primary)] text-[var(--color-primary)]" : "text-[var(--color-muted-foreground)]"}`} onClick={() => setTab(value)}>{value === "summary" ? "Resumo" : value === "requests" ? "Execuções" : "Timeline"}</button>)}</nav>
    {tab === "summary" && <Summary plan={plan} />}
    {tab === "requests" && (requests.loading && !requests.data ? <SkeletonList rows={6} /> : <div className="space-y-3"><Requests items={items} canEdit={canEdit} onGenerate={(item) => void openGeneration(item)} onDocument={setDocumentRequest} onReschedule={setRescheduling} onCancel={setCanceling} />{requests.data && <Pagination pagination={requests.data.pagination} onPageChange={setRequestPage} onPageSizeChange={(value) => { setRequestLimit(value); setRequestPage(1); }} />}</div>)}
    {tab === "timeline" && (history.loading && !history.data ? <SkeletonList rows={6} /> : <Timeline items={history.data ?? []} />)}

    <OperationCreationDrawer open={Boolean(generating)} mode="work-order" initialValues={prefill ?? undefined} submitOperation={submitOperation} submitLabel={`Criar OS da execução ${String(generating?.executionNumber ?? 0).padStart(3, "0")}`} contextNotice="Revise os dados desta execução programada. A Ordem de Serviço ficará disponível para gerenciamento normalmente." onClose={() => { setGenerating(null); setPrefill(null); }} />
    <RescheduleDrawer request={rescheduling} onClose={() => setRescheduling(null)} onSaved={() => { setRescheduling(null); setTick((value) => value + 1); }} />
    <DefaultsDrawer open={settings} plan={plan} onClose={() => setSettings(false)} onSaved={() => { setSettings(false); setTick((value) => value + 1); }} />
    <Drawer open={Boolean(documentRequest)} onClose={() => setDocumentRequest(null)} eyebrow="Documento PMOC" title={documentRequest ? `Execução ${String(documentRequest.executionNumber).padStart(3, "0")}` : "Documento"} width="max-w-[1280px]">
      {documentRequest?.operation && <div className="space-y-4">
        <div className="flex flex-wrap gap-2">
          <StatusChip tone={documentRequest.operation.signedAt ? "success" : "warning"}>{documentRequest.operation.signedAt ? "ASSINADO" : "NÃO ASSINADO"}</StatusChip>
          <StatusChip tone={(documentRequest.operation._count?.photos ?? 0) >= 4 ? "success" : "warning"}>{documentRequest.operation._count?.photos ?? 0}/4 imagens obrigatórias</StatusChip>
        </div>
        <p className="text-sm text-[var(--color-muted-foreground)]">O Preview pode ser consultado a qualquer momento. A geração do PDF final exige quatro imagens; quando o modelo solicitar coleta, o status permanecerá não assinado até a assinatura do cliente. Alterações posteriores tornam o PDF anterior desatualizado.</p>
        <DocumentViewer source={{ operationId: documentRequest.operation.id, type: "PMOC", documentId: documentRequest.operation.documents?.[0]?.id ?? null }} title={`PMOC · Execução ${String(documentRequest.executionNumber).padStart(3, "0")}`} onRendered={() => setTick((value) => value + 1)} />
      </div>}
    </Drawer>
    <ConfirmDialog open={Boolean(canceling)} title="Cancelar execução prevista?" danger confirmLabel="Cancelar execução" description="O número e todo o histórico serão preservados. A execução continuará disponível para consulta." onClose={() => setCanceling(null)} onConfirm={async () => { if (canceling) { await pmocApi.cancelExecutionRequest(canceling.id); setTick((value) => value + 1); } }} />
  </div>;
}

function Summary({ plan }: { plan: PmocPlan }) { const overview = plan.overview; const equipments = plan.equipments?.map((item) => item.equipment) ?? (plan.equipment ? [plan.equipment] : []); const scope = plan.scopes?.map((item) => item.technicalCatalog.title).join(" · ") || plan.coverage || "Não informado"; return <div className="grid gap-4 lg:grid-cols-2"><Card title="Plano e cliente"><Rows rows={[["Cliente", plan.customer?.tradeName ?? plan.customer?.name ?? "—"], ["Endereço", plan.defaultAddress ? [plan.defaultAddress.street, plan.defaultAddress.number, plan.defaultAddress.city].filter(Boolean).join(", ") : "Endereço padrão do cliente"], ["Escopo", scope], ["Periodicidade", periodicityLabel(plan.periodicity)], ["Período", `${date(plan.startDate)} até ${date(plan.endDate)}`], ["Programação", generationModeLabel(plan.generationMode)]]} /><div className="mt-4 flex flex-wrap gap-2">{plan.customer && <Link className={smallLink} href={`/clientes/${plan.customer.id}`}>Abrir cliente</Link>}{equipments.map((equipment) => <Link key={equipment.id} className={smallLink} href={`/equipamentos/${equipment.id}`}>{equipment.name}</Link>)}</div></Card><Card title="Operação"><Rows rows={[["Tipos de serviço", (plan.serviceTypes.length ? plan.serviceTypes : [plan.defaultOperationType]).map(operationTypeLabel).join(" · ")], ["Próxima execução", date(plan.nextExecutionDate)], ["Última execução", date(overview?.lastExecutionDate ?? plan.lastExecutionDate)], ["Operador padrão", plan.defaultOperator?.name ?? "Definido ao gerar"], ["Técnico padrão", plan.defaultTechnician?.name ?? plan.responsibleTechnician], ["Última OS", overview?.lastOperation ? `OS-${String(overview.lastOperation.number).padStart(6, "0")}` : "—"], ["Último documento", overview?.lastDocument?.number ?? "—"]]} /><div className="mt-4 flex gap-2">{overview?.lastOperation && <Link className={smallLink} href={`/operacoes?operationId=${overview.lastOperation.id}`}>Abrir última OS</Link>}{overview?.lastDocument && <Link className={smallLink} href={`/documentos?documentId=${overview.lastDocument.id}`}>Abrir documento</Link>}</div></Card><Card title="Assinatura"><Rows rows={[["Assinatura utilizada", plan.signatureOverride?.name ?? "Definida pelo modelo do documento"], ["Cargo", plan.signatureOverride?.title ?? "—"], ["Conselho", plan.signatureOverride?.professionalCouncil ?? "—"]]} /></Card><Card title="Saúde e automação"><Rows rows={[["Saúde", overview ? `${overview.health.label} · ${overview.health.score}/100` : "—"], ["Atrasadas", String(overview?.overdueExecutions ?? 0)], ["Atraso médio", `${overview?.averageDelayDays ?? 0} dia(s)`], ["Última verificação automática", dateTime(plan.lastSchedulerRun)], ["Situação da geração automática", schedulerStatusLabel(plan.lastSchedulerStatus)]]} /></Card></div>; }

function Requests({ items, canEdit, onGenerate, onDocument, onReschedule, onCancel }: { items: PmocExecutionRequest[]; canEdit: boolean; onGenerate: (item: PmocExecutionRequest) => void; onDocument: (item: PmocExecutionRequest) => void; onReschedule: (item: PmocExecutionRequest) => void; onCancel: (item: PmocExecutionRequest) => void }) {
  if (!items.length) return <EmptyState icon={CalendarClock} title="Sem execuções" description="As execuções previstas aparecerão aqui." />;
  return <div className="overflow-x-auto rounded-xl border border-[var(--color-border)]"><table className="w-full text-sm"><thead className="bg-[var(--color-muted)] text-left text-xs uppercase text-[var(--color-muted-foreground)]"><tr><th className="p-3">Execução</th><th className="p-3">Origem</th><th className="p-3">Status</th><th className="p-3">Prevista</th><th className="p-3">Gerada</th><th className="p-3">OS</th><th className="p-3">Operador</th><th className="p-3">Técnico</th><th className="p-3">Documento</th><th className="p-3 text-right">Ações</th></tr></thead><tbody>{items.map((item) => {
    const document = item.operation?.documents?.[0];
    return <tr key={item.id} className="border-t border-[var(--color-border)]"><td className="p-3 font-semibold">{String(item.executionNumber).padStart(3, "0")}</td><td className="p-3">{item.origin === "AUTO" ? "Automática" : "Manual"}</td><td className="p-3"><StatusChip tone={item.status === "FAILED" ? "danger" : item.status === "CANCELLED" ? "warning" : item.status === "GENERATED" ? "success" : "info"}>{executionStatusLabel(item.status)}</StatusChip></td><td className="p-3">{dateTime(item.scheduledFor)}</td><td className="p-3">{dateTime(item.generatedAt)}</td><td className="p-3">{item.operation ? <Link className="text-[var(--color-primary)]" href={`/operacoes?operationId=${item.operation.id}`}>OS-{String(item.operation.number).padStart(6, "0")}</Link> : "—"}</td><td className="p-3">{item.operation?.operator?.name ?? item.plannedOperator?.name ?? "—"}</td><td className="p-3">{item.plannedTechnician?.name ?? "—"}</td><td className="p-3">{item.operation ? <button className="text-left text-[var(--color-primary)]" onClick={() => onDocument(item)}><span className="inline-flex items-center gap-1"><FileText className="h-3.5 w-3.5" />{document?.number ?? "Preparar documento"}</span><span className={`block text-[11px] ${item.operation.signedAt ? "text-emerald-600" : "text-amber-600"}`}>{item.operation.signedAt ? "Assinado" : "Não assinado"} · {item.operation._count?.photos ?? 0}/4 imagens</span></button> : "—"}</td><td className="p-3"><div className="flex justify-end gap-1">{item.operation && <button title="Preview, gerar e baixar PMOC" className={iconBtn} onClick={() => onDocument(item)}><FileText className="h-4 w-4" /></button>}{item.operation && <Link title="Abrir OS" className={iconBtn} href={`/operacoes?operationId=${item.operation.id}`}><CalendarClock className="h-4 w-4" /></Link>}{canEdit && (item.status === "PENDING" || item.status === "FAILED") && <><button title="Gerar OS" className={iconBtn} onClick={() => onGenerate(item)}><Play className="h-4 w-4" /></button><button title="Reagendar" className={iconBtn} onClick={() => onReschedule(item)}><RefreshCw className="h-4 w-4" /></button><button title="Cancelar" className={`${iconBtn} text-red-600`} onClick={() => onCancel(item)}><XCircle className="h-4 w-4" /></button></>}</div></td></tr>;
  })}</tbody></table></div>;
}

function Timeline({ items }: { items: PmocHistoryItem[] }) { if (!items.length) return <EmptyState icon={History} title="Sem histórico" description="As movimentações deste PMOC aparecerão aqui." />; return <ol className="relative ml-3 border-l border-[var(--color-border)] pl-6">{items.map((item) => <li key={item.id} className="relative pb-6"><span className="absolute -left-[31px] top-1 h-3 w-3 rounded-full border-2 border-[var(--color-card)] bg-[var(--color-primary)]" /><div className="flex flex-wrap items-center gap-2"><strong className="text-sm">{historyLabel(item.action)}</strong>{item.source && <StatusChip tone="info">{historySourceLabel(item.source)}</StatusChip>}{item.execution && <StatusChip tone="info">Execução {String(item.execution.executionNumber).padStart(3, "0")}</StatusChip>}</div><p className="mt-1 text-xs text-[var(--color-muted-foreground)]">{dateTime(item.occurredAt)} · {item.actor?.name ?? (item.actorId ? "usuário responsável" : "automação do sistema")}</p>{item.execution && <p className="mt-1 text-sm">{item.execution.workOrderNumber ? `OS-${String(item.execution.workOrderNumber).padStart(6, "0")} · ` : ""}{item.execution.operator?.name ?? "Sem operador"}</p>}{item.document && <Link href={`/documentos?documentId=${item.document.id}`} className="mt-1 inline-flex items-center gap-1 text-sm text-[var(--color-primary)]"><FileText className="h-3.5 w-3.5" /> {item.document.number}</Link>}{item.notes && <p className="mt-1 text-sm text-[var(--color-muted-foreground)]">{item.notes}</p>}</li>)}</ol>; }

function RescheduleDrawer({ request, onClose, onSaved }: { request: PmocExecutionRequest | null; onClose: () => void; onSaved: () => void }) { const [value, setValue] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); useEffect(() => { setValue(request?.scheduledFor ? new Date(request.scheduledFor).toISOString().slice(0, 10) : ""); setError(null); }, [request]); return <Drawer open={Boolean(request)} onClose={onClose} title={`Editar data da execução ${String(request?.executionNumber ?? 0).padStart(3, "0")}`} eyebrow="Próximas execuções" footer={<><button className={secondary} onClick={onClose}>Cancelar</button><button className={primary} disabled={!value || busy} onClick={async () => { if (!request) return; setBusy(true); setError(null); try { await pmocApi.rescheduleExecutionRequest(request.id, { scheduledFor: new Date(`${value}T12:00:00`).toISOString(), notes: "Data ajustada individualmente pela gestão do PMOC" }); onSaved(); } catch (cause) { setError(message(cause)); } finally { setBusy(false); } }}>Salvar nova data</button></>}><div className="space-y-3">{error && <div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-700">{error}</div>}<label className="grid gap-2 text-sm font-medium">Data prevista<input type="date" value={value} onChange={(event) => setValue(event.target.value)} /></label><p className="text-sm text-[var(--color-muted-foreground)]">Somente a execução {String(request?.executionNumber ?? 0).padStart(3, "0")} será alterada. A periodicidade, as demais datas, o número e o histórico permanecem preservados.</p></div></Drawer>; }

function DefaultsDrawer({ open, plan, onClose, onSaved }: { open: boolean; plan: PmocPlan; onClose: () => void; onSaved: () => void }) { const users = useQuery((signal) => usersApi.listUsers({ limit: 100, signal }), []); const [operatorId, setOperatorId] = useState(plan.defaultOperatorId ?? ""); const [technicianId, setTechnicianId] = useState(plan.defaultTechnicianId ?? ""); const [propagate, setPropagate] = useState(false); const [busy, setBusy] = useState(false); const available = users.data?.items.filter((item) => item.isActive && item.role !== "VIEWER") ?? []; return <Drawer open={open} onClose={onClose} title="Responsáveis padrão" eyebrow="PMOC" footer={<><button className={secondary} onClick={onClose}>Cancelar</button><button className={primary} disabled={busy} onClick={async () => { setBusy(true); try { await pmocApi.updatePmoc(plan.id, { defaultOperatorId: operatorId || null, defaultTechnicianId: technicianId || null, responsibleTechnician: available.find((item) => item.id === technicianId)?.name ?? plan.responsibleTechnician, applyDefaultsToPendingExecutions: propagate }); onSaved(); } finally { setBusy(false); } }}>Salvar</button></>}><div className="space-y-4"><label className="grid gap-2 text-sm font-medium">Operador padrão<select value={operatorId} onChange={(event) => setOperatorId(event.target.value)}><option value="">Definir ao gerar</option>{available.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.role}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">Técnico padrão<select value={technicianId} onChange={(event) => setTechnicianId(event.target.value)}><option value="">Sem técnico padrão</option>{available.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.jobTitle ?? item.role}</option>)}</select></label><label className="flex items-start gap-3 rounded-lg border border-[var(--color-border)] p-3 text-sm"><input className="mt-1" type="checkbox" checked={propagate} onChange={(event) => setPropagate(event.target.checked)} /><span><strong>Aplicar também às próximas execuções pendentes?</strong><span className="block text-xs text-[var(--color-muted-foreground)]">Execuções concluídas e OS já geradas nunca serão alteradas.</span></span></label></div></Drawer>; }

function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-5"><h2 className="mb-4 font-semibold">{title}</h2>{children}</section>; }
function Rows({ rows }: { rows: Array<[string, string]> }) { return <dl className="space-y-3">{rows.map(([label, value]) => <div key={label} className="flex justify-between gap-4 border-b border-[var(--color-border)]/70 pb-2 last:border-0"><dt className="text-sm text-[var(--color-muted-foreground)]">{label}</dt><dd className="text-right text-sm font-medium">{value}</dd></div>)}</dl>; }
function Metric({ label, value, tone }: { label: string; value: string | number; tone?: "danger" }) { return <div className="rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-3"><strong className={tone === "danger" ? "text-xl text-red-600" : "text-xl"}>{value}</strong><span className="block text-xs text-[var(--color-muted-foreground)]">{label}</span></div>; }
function historyLabel(action: string) { const labels: Record<string, string> = { CREATED: "Plano criado", PERIODICITY_CHANGED: "Periodicidade alterada", OPERATOR_CHANGED: "Operador alterado", REQUEST_CREATED: "Execução criada", REQUEST_CREATED_AUTO: "Execução automática criada", REQUEST_CREATED_MANUAL: "Execução manual criada", OS_GENERATED_AUTO: "OS gerada automaticamente", OS_GENERATED_MANUAL: "OS gerada manualmente", ASSIGNMENT_ACCEPTED: "Operador aceitou", ASSIGNMENT_STARTED: "Execução iniciada", ASSIGNMENT_COMPLETED: "Atendimento concluído", EXECUTION_COMPLETED: "Execução concluída", DOCUMENT_RENDERED: "Documento emitido", CLIENT_SIGNED: "Cliente assinou", REQUEST_CANCELLED: "Execução cancelada", REQUEST_FAILED: "Falha na execução" }; return labels[action] ?? "Atualização do PMOC"; }
function historySourceLabel(source: string) { return ({ PMOC: "PMOC", ASSIGNMENT: "Atendimento", DOCUMENT: "Documento", AUDIT: "Registro operacional" } as Record<string, string>)[source] ?? "Atualização"; }
function periodicityLabel(value: string) { return ({ WEEKLY: "Semanal", BIWEEKLY: "Quinzenal", MONTHLY: "Mensal", BIMONTHLY: "Bimestral", QUARTERLY: "Trimestral", FOUR_MONTHLY: "Quadrimestral", SEMIANNUAL: "Semestral", YEARLY: "Anual", CUSTOM: "Personalizada" } as Record<string, string>)[value] ?? value; }
function generationModeLabel(value: string) { return ({ AUTO: "Geração automática", MANUAL: "Geração com revisão", PAUSED: "Programação pausada" } as Record<string, string>)[value] ?? value; }
function operationalStatusLabel(value: string) { return ({ ACTIVE: "Ativo", PENDING: "Aguardando início", OVERDUE: "Atrasado", PAUSED: "Pausado", ERROR: "Requer atenção", EXPIRED: "Encerrado" } as Record<string, string>)[value] ?? "Em acompanhamento"; }
function schedulerStatusLabel(value: string) { return ({ NEVER_RUN: "Nenhuma geração automática realizada", RUNNING: "Verificação automática em andamento", SUCCESS: "Última geração concluída", PARTIAL_FAILURE: "Algumas Ordens de Serviço requerem atenção", FAILED: "Não foi possível concluir a última geração" } as Record<string, string>)[value] ?? "Sem informação"; }
function operationTypeLabel(value: string) { return ({ PREVENTIVA: "Manutenção preventiva", CORRETIVA: "Manutenção corretiva", INSTALACAO: "Instalação", PROJETO: "Projeto / inspeção técnica" } as Record<string, string>)[value] ?? value; }
function executionStatusLabel(value: string) { return ({ PENDING: "Aguardando geração", GENERATING_OS: "Preparando Ordem de Serviço", GENERATED: "Ordem de Serviço criada", FAILED: "Requer atenção", CANCELLED: "Cancelada" } as Record<string, string>)[value] ?? "Em processamento"; }
function date(value: string | null) { return value ? new Date(value).toLocaleDateString("pt-BR") : "—"; }
function dateTime(value: string | null) { return value ? new Date(value).toLocaleString("pt-BR") : "—"; }
function message(cause: unknown) { return cause instanceof ApiClientError ? cause.message : cause instanceof Error ? cause.message : "Não foi possível concluir a ação."; }
const primary = "inline-flex h-10 items-center gap-2 rounded-[var(--radius-md)] bg-[var(--color-primary)] px-4 text-sm font-medium text-[var(--color-primary-foreground)] disabled:opacity-50";
const secondary = "inline-flex h-10 items-center gap-2 rounded-[var(--radius-md)] border border-[var(--color-border)] px-4 text-sm font-medium";
const iconBtn = "grid h-9 w-9 place-items-center rounded-md border border-[var(--color-border)] hover:bg-[var(--color-muted)]";
const smallLink = "inline-flex rounded-md border border-[var(--color-border)] px-2.5 py-1.5 text-xs font-medium hover:bg-[var(--color-muted)]";
