export const ASSET_LIFECYCLE_RESOURCE = 'ASSET_LIFECYCLE_EVENT';
export const ASSET_LIFECYCLE_ATTACHMENT_RESOURCE = 'ASSET_LIFECYCLE_ATTACHMENT';
export const ASSET_LIFECYCLE_STORAGE_PREFIX = 'asset-lifecycle';

export const ASSET_LIFECYCLE_AUDIT_ACTIONS = {
  EVENT_CREATED: 'ASSET_LIFECYCLE_EVENT_CREATED',
  EVENT_AUTO_CREATED: 'ASSET_LIFECYCLE_EVENT_AUTO_CREATED',
  ATTACHMENT_UPLOADED: 'ASSET_LIFECYCLE_ATTACHMENT_UPLOADED',
  ATTACHMENT_DELETED: 'ASSET_LIFECYCLE_ATTACHMENT_DELETED',
} as const;

export const MAX_ASSET_LIFECYCLE_ATTACHMENT_SIZE_BYTES = 5 * 1024 * 1024;

export const ASSET_LIFECYCLE_ATTACHMENT_MIME_TYPES = [
  'application/pdf',
  'image/png',
  'image/jpeg',
] as const;

export const ASSET_LIFECYCLE_ATTACHMENT_EXTENSIONS = ['pdf', 'png', 'jpg', 'jpeg'] as const;
