export const ASSIGNMENT_RESOURCE = 'ASSIGNMENT';

export const ASSIGNMENT_AUDIT_ACTIONS = {
  ASSIGNMENT_CREATED: 'ASSIGNMENT_CREATED',
  ASSIGNMENT_REASSIGNED: 'ASSIGNMENT_REASSIGNED',
  ASSIGNMENT_ACCEPTED: 'ASSIGNMENT_ACCEPTED',
  ASSIGNMENT_STARTED: 'ASSIGNMENT_STARTED',
  ASSIGNMENT_REJECTED: 'ASSIGNMENT_REJECTED',
  ASSIGNMENT_COMPLETED: 'ASSIGNMENT_COMPLETED',
} as const;
