export const BUDGET_RESOURCE = 'BUDGET';

export const BUDGET_AUDIT_ACTIONS = {
  BUDGET_CREATED: 'BUDGET_CREATED',
  BUDGET_UPDATED: 'BUDGET_UPDATED',
  BUDGET_APPROVED: 'BUDGET_APPROVED',
  BUDGET_REJECTED: 'BUDGET_REJECTED',
  BUDGET_CANCELED: 'BUDGET_CANCELED',
  BUDGET_HISTORY_CREATED: 'BUDGET_HISTORY_CREATED',
} as const;
