export const CUSTOMER_RESOURCE = 'CUSTOMER';
export const CUSTOMER_ADDRESS_RESOURCE = 'CUSTOMER_ADDRESS';
export const CUSTOMER_CONTACT_RESOURCE = 'CUSTOMER_CONTACT';
export const CUSTOMER_ATTACHMENT_RESOURCE = 'CUSTOMER_ATTACHMENT';

export const CUSTOMER_AUDIT_ACTIONS = {
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  CUSTOMER_DISABLED: 'CUSTOMER_DISABLED',
  CUSTOMER_ENABLED: 'CUSTOMER_ENABLED',
  CUSTOMER_DELETED: 'CUSTOMER_DELETED',
  CUSTOMER_ADDRESS_CREATED: 'CUSTOMER_ADDRESS_CREATED',
  CUSTOMER_ADDRESS_UPDATED: 'CUSTOMER_ADDRESS_UPDATED',
  CUSTOMER_ADDRESS_DELETED: 'CUSTOMER_ADDRESS_DELETED',
  CUSTOMER_CONTACT_CREATED: 'CUSTOMER_CONTACT_CREATED',
  CUSTOMER_CONTACT_UPDATED: 'CUSTOMER_CONTACT_UPDATED',
  CUSTOMER_CONTACT_DELETED: 'CUSTOMER_CONTACT_DELETED',
  CUSTOMER_ATTACHMENT_UPLOADED: 'CUSTOMER_ATTACHMENT_UPLOADED',
  CUSTOMER_ATTACHMENT_DELETED: 'CUSTOMER_ATTACHMENT_DELETED',
} as const;

export const MAX_CUSTOMER_ATTACHMENT_SIZE_BYTES = 5 * 1024 * 1024;
export const CUSTOMER_ATTACHMENT_EXTENSIONS = ['pdf', 'png', 'jpg', 'jpeg'] as const;
export const CUSTOMER_ATTACHMENT_MIME_TYPES = [
  'application/pdf',
  'image/png',
  'image/jpeg',
] as const;
