export const EQUIPMENT_RESOURCE = 'EQUIPMENT';
export const EQUIPMENT_ATTACHMENT_RESOURCE = 'EQUIPMENT_ATTACHMENT';
export const EQUIPMENT_METRIC_RESOURCE = 'EQUIPMENT_METRIC';

export const EQUIPMENT_AUDIT_ACTIONS = {
  EQUIPMENT_CREATED: 'EQUIPMENT_CREATED',
  EQUIPMENT_UPDATED: 'EQUIPMENT_UPDATED',
  EQUIPMENT_DISABLED: 'EQUIPMENT_DISABLED',
  EQUIPMENT_ENABLED: 'EQUIPMENT_ENABLED',
  EQUIPMENT_DELETED: 'EQUIPMENT_DELETED',
  EQUIPMENT_ATTACHMENT_UPLOADED: 'EQUIPMENT_ATTACHMENT_UPLOADED',
  EQUIPMENT_ATTACHMENT_DELETED: 'EQUIPMENT_ATTACHMENT_DELETED',
  EQUIPMENT_METRIC_CREATED: 'EQUIPMENT_METRIC_CREATED',
  EQUIPMENT_METRIC_DELETED: 'EQUIPMENT_METRIC_DELETED',
} as const;

export const MAX_EQUIPMENT_ATTACHMENT_SIZE_BYTES = 5 * 1024 * 1024;
export const EQUIPMENT_ATTACHMENT_EXTENSIONS = ['pdf', 'png', 'jpg', 'jpeg'] as const;
export const EQUIPMENT_ATTACHMENT_MIME_TYPES = [
  'application/pdf',
  'image/png',
  'image/jpeg',
] as const;
