export const FINANCIAL_RESOURCE = 'FINANCIAL';
export const FINANCIAL_ACCOUNT_RESOURCE = 'FINANCIAL_ACCOUNT';
export const FINANCIAL_CATEGORY_RESOURCE = 'FINANCIAL_CATEGORY';
export const FINANCIAL_ENTRY_RESOURCE = 'FINANCIAL_ENTRY';

export const FINANCIAL_AUDIT_ACTIONS = {
  ACCOUNT_CREATED: 'FINANCIAL_ACCOUNT_CREATED',
  ACCOUNT_UPDATED: 'FINANCIAL_ACCOUNT_UPDATED',
  ACCOUNT_DELETED: 'FINANCIAL_ACCOUNT_DELETED',
  CATEGORY_CREATED: 'FINANCIAL_CATEGORY_CREATED',
  CATEGORY_UPDATED: 'FINANCIAL_CATEGORY_UPDATED',
  CATEGORY_DELETED: 'FINANCIAL_CATEGORY_DELETED',
  ENTRY_CREATED: 'FINANCIAL_ENTRY_CREATED',
  ENTRY_UPDATED: 'FINANCIAL_ENTRY_UPDATED',
  ENTRY_PAID: 'FINANCIAL_ENTRY_PAID',
  ENTRY_CANCELED: 'FINANCIAL_ENTRY_CANCELED',
} as const;
