export const PRODUCT_RESOURCE = 'PRODUCT';
export const INVENTORY_RESOURCE = 'INVENTORY_ITEM';
export const STOCK_MOVEMENT_RESOURCE = 'STOCK_MOVEMENT';
export const SUPPLIER_RESOURCE = 'SUPPLIER';
export const OPERATION_PART_RESOURCE = 'OPERATION_PART';

export const INVENTORY_AUDIT_ACTIONS = {
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  SUPPLIER_CREATED: 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED: 'SUPPLIER_UPDATED',
  SUPPLIER_DELETED: 'SUPPLIER_DELETED',
  INVENTORY_ITEM_CREATED: 'INVENTORY_ITEM_CREATED',
  INVENTORY_ITEM_UPDATED: 'INVENTORY_ITEM_UPDATED',
  STOCK_MOVEMENT_CREATED: 'STOCK_MOVEMENT_CREATED',
  MATERIAL_CONSUMED: 'MATERIAL_CONSUMED',
  MATERIAL_RETURNED: 'MATERIAL_RETURNED',
} as const;
