export const MAINTENANCE_PLAN_RESOURCE = 'MAINTENANCE_PLAN';
export const MAINTENANCE_EXECUTION_RESOURCE = 'MAINTENANCE_EXECUTION';

export const MAINTENANCE_AUDIT_ACTIONS = {
  PLAN_CREATED: 'MAINTENANCE_PLAN_CREATED',
  PLAN_UPDATED: 'MAINTENANCE_PLAN_UPDATED',
  PLAN_DELETED: 'MAINTENANCE_PLAN_DELETED',
  EXECUTION_CREATED: 'MAINTENANCE_EXECUTION_CREATED',
  EXECUTION_UPDATED: 'MAINTENANCE_EXECUTION_UPDATED',
  EXECUTION_COMPLETED: 'MAINTENANCE_EXECUTION_COMPLETED',
} as const;
