export const MAINTENANCE_CHECKLIST_TEMPLATE_RESOURCE = 'MAINTENANCE_CHECKLIST_TEMPLATE';

export const MAINTENANCE_CHECKLIST_TEMPLATE_AUDIT_ACTIONS = {
  CREATED: 'MAINTENANCE_CHECKLIST_TEMPLATE_CREATED',
  UPDATED: 'MAINTENANCE_CHECKLIST_TEMPLATE_UPDATED',
  DEACTIVATED: 'MAINTENANCE_CHECKLIST_TEMPLATE_DEACTIVATED',
} as const;
