export const ORGANIZATION_RESOURCE = 'ORGANIZATION';
export const ORGANIZATION_SETTINGS_RESOURCE = 'ORGANIZATION_SETTINGS';
export const DOCUMENT_TEMPLATE_RESOURCE = 'DOCUMENT_TEMPLATE';
export const BRAND_ASSET_RESOURCE = 'BRAND_ASSET';

export const ORGANIZATION_AUDIT_ACTIONS = {
  ORGANIZATION_UPDATED: 'ORGANIZATION_UPDATED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  TEMPLATE_CREATED: 'TEMPLATE_CREATED',
  TEMPLATE_UPDATED: 'TEMPLATE_UPDATED',
  TEMPLATE_DELETED: 'TEMPLATE_DELETED',
  ASSET_UPLOADED: 'ASSET_UPLOADED',
  ASSET_DELETED: 'ASSET_DELETED',
} as const;

export const MAX_BRAND_ASSET_SIZE_BYTES = 5 * 1024 * 1024;

export const ALLOWED_BRAND_ASSET_MIME_TYPES = [
  'image/png',
  'image/jpeg',
  'image/svg+xml',
  'application/pdf',
] as const;

export const ALLOWED_BRAND_ASSET_EXTENSIONS = ['png', 'jpg', 'jpeg', 'svg', 'pdf'] as const;
