export const PMOC_RESOURCE = 'PMOC';
export const PMOC_ENVIRONMENT_RESOURCE = 'PMOC_ENVIRONMENT';

export const PMOC_AUDIT_ACTIONS = {
  CREATED: 'PMOC_CREATED',
  UPDATED: 'PMOC_UPDATED',
  DELETED: 'PMOC_DELETED',
  ENVIRONMENT_CREATED: 'PMOC_ENVIRONMENT_CREATED',
  ENVIRONMENT_UPDATED: 'PMOC_ENVIRONMENT_UPDATED',
  ENVIRONMENT_DELETED: 'PMOC_ENVIRONMENT_DELETED',
} as const;
