export const PMOC_RESOURCE = 'PMOC';
export const PMOC_ENVIRONMENT_RESOURCE = 'PMOC_ENVIRONMENT';
export const PMOC_EXECUTION_REQUEST_RESOURCE = 'PMOC_EXECUTION_REQUEST';

/** Minimum field evidence required before a PMOC execution can be completed or emitted. */
export const PMOC_MIN_PROCEDURE_IMAGES = 4;

export const PMOC_AUDIT_ACTIONS = {
  CREATED: 'PMOC_CREATED',
  ACTIVE_COVERAGE_CONFIRMED: 'PMOC_ACTIVE_COVERAGE_CONFIRMED',
  UPDATED: 'PMOC_UPDATED',
  DELETED: 'PMOC_DELETED',
  ENVIRONMENT_CREATED: 'PMOC_ENVIRONMENT_CREATED',
  ENVIRONMENT_UPDATED: 'PMOC_ENVIRONMENT_UPDATED',
  ENVIRONMENT_DELETED: 'PMOC_ENVIRONMENT_DELETED',
  EXECUTION_REQUEST_CREATED: 'PMOC_EXECUTION_REQUEST_CREATED',
  EXECUTION_REQUEST_CREATED_AUTO: 'PMOC_EXECUTION_REQUEST_CREATED_AUTO',
  EXECUTION_REQUEST_CREATED_MANUAL: 'PMOC_EXECUTION_REQUEST_CREATED_MANUAL',
  EXECUTION_REQUEST_RETRIED: 'PMOC_EXECUTION_REQUEST_RETRIED',
  EXECUTION_REQUEST_GENERATING: 'PMOC_EXECUTION_REQUEST_GENERATING',
  EXECUTION_REQUEST_GENERATED: 'PMOC_EXECUTION_REQUEST_GENERATED',
  EXECUTION_REQUEST_FAILED: 'PMOC_EXECUTION_REQUEST_FAILED',
  EXECUTION_REQUEST_CANCELLED: 'PMOC_EXECUTION_REQUEST_CANCELLED',
  EXECUTION_REQUEST_RESCHEDULED: 'PMOC_EXECUTION_REQUEST_RESCHEDULED',
  EXECUTION_REQUEST_EARLY: 'PMOC_EXECUTION_REQUEST_EARLY',
  DEFAULTS_PROPAGATED: 'PMOC_DEFAULTS_PROPAGATED',
  SCHEDULER_RUN: 'PMOC_SCHEDULER_RUN',
} as const;
