export const PRICING_RESOURCE = 'PRODUCT_PRICING';

export const PRICING_AUDIT_ACTIONS = {
  PRICING_CREATED: 'PRICING_CREATED',
  PRICING_UPDATED: 'PRICING_UPDATED',
  PRICING_DEACTIVATED: 'PRICING_DEACTIVATED',
  PRICING_RESOLVED: 'PRICING_RESOLVED',
} as const;
