export const PROCUREMENT_RESOURCE = 'PROCUREMENT';
export const PURCHASE_ORDER_RESOURCE = 'PURCHASE_ORDER';
export const PURCHASE_ITEM_RESOURCE = 'PURCHASE_ORDER_ITEM';
export const PURCHASE_RECEIPT_RESOURCE = 'PURCHASE_RECEIPT';

export const PROCUREMENT_AUDIT_ACTIONS = {
  ORDER_CREATED: 'PURCHASE_ORDER_CREATED',
  ORDER_UPDATED: 'PURCHASE_ORDER_UPDATED',
  ORDER_SENT: 'PURCHASE_ORDER_SENT',
  ORDER_CANCELED: 'PURCHASE_ORDER_CANCELED',
  ITEM_CREATED: 'PURCHASE_ITEM_CREATED',
  ITEM_UPDATED: 'PURCHASE_ITEM_UPDATED',
  ITEM_DELETED: 'PURCHASE_ITEM_DELETED',
  RECEIPT_CREATED: 'PURCHASE_RECEIPT_CREATED',
} as const;
