export const SALE_RESOURCE = 'Sale';

export const SALE_AUDIT_ACTIONS = {
  SALE_CREATED: 'SALE_CREATED',
  SALE_UPDATED: 'SALE_UPDATED',
  SALE_COMPLETED: 'SALE_COMPLETED',
  SALE_CANCELED: 'SALE_CANCELED',
  SALE_RECEIPT_LINKED: 'SALE_RECEIPT_LINKED',
} as const;
