export const SIGNATURE_RESOURCE = 'SIGNATURE';

export const SIGNATURE_AUDIT_ACTIONS = {
  SIGNATURE_CREATED: 'SIGNATURE_CREATED',
  SIGNATURE_UPDATED: 'SIGNATURE_UPDATED',
  SIGNATURE_DELETED: 'SIGNATURE_DELETED',
  SIGNATURE_IMAGE_UPLOADED: 'SIGNATURE_IMAGE_UPLOADED',
  SIGNATURE_IMAGE_DOWNLOADED: 'SIGNATURE_IMAGE_DOWNLOADED',
} as const;

export const SIGNATURE_STORAGE_PREFIX = 'documents/signatures';
export const MAX_SIGNATURE_IMAGE_SIZE_BYTES = 2 * 1024 * 1024;
export const SIGNATURE_IMAGE_MIME_TYPES = ['image/png', 'image/jpeg'] as const;
export const SIGNATURE_IMAGE_EXTENSIONS = ['png', 'jpg', 'jpeg'] as const;
