"use client";

/**
 * ExportButton — exports the current on-screen rows.
 *
 * CSV is produced client-side for visible rows. PDF is generated by backend
 * export endpoints using the active filter context supplied by each page.
 */
import { useEffect, useRef, useState } from "react";
import { Download, FileSpreadsheet, FileText, ChevronDown } from "lucide-react";
import { exportCsv } from "@erp/utils";

export function ExportButton<T extends Record<string, unknown>>({
  rows,
  fileName,
  columns,
  label = "Exportar",
  disabled = false,
  onPdf,
  pdfDisabled = false,
}: {
  rows: T[];
  fileName: string;
  columns?: string[];
  label?: string;
  disabled?: boolean;
  onPdf?: () => Promise<{ blob: Blob; filename?: string | null }>;
  pdfDisabled?: boolean;
}) {
  const [open, setOpen] = useState(false);
  const [pdfPending, setPdfPending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function onClick(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", onClick);
    return () => document.removeEventListener("mousedown", onClick);
  }, []);

  function handleCsv() {
    exportCsv(rows as Array<Record<string, unknown>>, fileName, columns);
    setOpen(false);
  }

  async function handlePdf() {
    if (!onPdf || pdfPending) return;
    setPdfPending(true);
    setError(null);
    try {
      const result = await onPdf();
      downloadBlob(result.blob, result.filename ?? `${fileName}-${new Date().toISOString().slice(0, 10)}.pdf`);
      setOpen(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Não foi possível gerar o PDF.");
    } finally {
      setPdfPending(false);
    }
  }

  return (
    <div className="relative" ref={ref}>
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        disabled={disabled || rows.length === 0}
        className="inline-flex items-center gap-2 rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-card)] px-3 h-9 text-sm hover:bg-[var(--color-muted)] disabled:opacity-50"
      >
        <Download className="h-4 w-4" /> {label}
        <ChevronDown className="h-3.5 w-3.5" />
      </button>

      {open && (
        <div className="absolute right-0 mt-2 w-52 rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-card)] shadow-[var(--shadow-floating)] p-1.5 z-20 animate-slide-up">
          <button
            type="button"
            onClick={handleCsv}
            className="w-full inline-flex items-center gap-2 rounded-[var(--radius-md)] px-3 py-2 text-sm hover:bg-[var(--color-muted)]"
          >
            <FileSpreadsheet className="h-4 w-4" /> Planilha (CSV)
          </button>
          <button
            type="button"
            onClick={handlePdf}
            disabled={!onPdf || pdfDisabled || pdfPending}
            title={!onPdf ? "Exportação PDF indisponível nesta tela." : undefined}
            className="w-full inline-flex items-center gap-2 rounded-[var(--radius-md)] px-3 py-2 text-sm hover:bg-[var(--color-muted)] disabled:text-[var(--color-muted-foreground)] disabled:opacity-60 disabled:cursor-not-allowed"
          >
            <FileText className="h-4 w-4" /> {pdfPending ? "Gerando PDF…" : "PDF"}
            <span className="ml-auto text-[9px] uppercase tracking-wider rounded bg-[var(--color-muted)] px-1.5 py-0.5">backend</span>
          </button>
          {error && <div className="px-3 py-2 text-xs text-[var(--color-danger)]">{error}</div>}
        </div>
      )}
    </div>
  );
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = safeFilename(filename);
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

function safeFilename(value: string): string {
  return value.replace(/[^\w.\-]+/g, "-").replace(/-+/g, "-").slice(0, 160) || "orbit-export.pdf";
}
