'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useState } from 'react';
import { ArrowLeft, CalendarDays, Download, FileText, Pencil, Play, UserPlus, UserRound, Wrench } from 'lucide-react';
import { PageHeader } from '@platform/components/page-header';
import { Pagination } from '@platform/components/pagination';
import { OperationDetailDrawer } from '@platform/components/operation-detail-drawer';
import { RvtExecutionDrawer } from '@platform/components/rvt-execution-drawer';
import { RvtPlanWizard } from '@platform/components/rvt-plan-wizard';
import { assignmentsApi, documentsApi, rvtApi, useQuery, ApiClientError, type RvtExecutionStatus } from '@erp/api';
import { useAuth } from '@erp/ui/auth/auth-provider';
import { EmptyState } from '@erp/ui/empty-state';
import { ErrorState } from '@erp/ui/states';
import { SkeletonList } from '@erp/ui/skeletons';
import { StatusChip } from '@erp/ui/status-chip';

export default function RvtDetailPage() {
  const { id } = useParams<{ id: string }>(); const { hasRole, session } = useAuth(); const canEdit = hasRole('OWNER', 'MANAGER');
  const [page, setPage] = useState(1); const [limit, setLimit] = useState(20); const [edit, setEdit] = useState(false); const [detailOperationId, setDetailOperationId] = useState<string | null>(null); const [executionAssignmentId, setExecutionAssignmentId] = useState<string | null>(null); const [tick, setTick] = useState(0); const [busyId, setBusyId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const plan = useQuery((signal) => rvtApi.getPlan(id, { signal }), [id, tick]);
  const executions = useQuery((signal) => rvtApi.listExecutions(id, { page, limit, signal }), [id, page, limit, tick]);
  async function prepare(executionId: string, executeNow = false) { setBusyId(executionId); setError(null); try { const operation = await rvtApi.prepareExecution(executionId, executeNow ? session?.user.id : undefined); if (executeNow) { if (!session?.user.id) throw new Error('Sessão inválida. Entre novamente para executar o RVT.'); let assignment = operation.assignment; if (!assignment) throw new Error('A execução foi preparada, mas a atribuição não foi localizada.'); if (assignment.assignedTo !== session.user.id) assignment = await assignmentsApi.reassignAssignment(assignment.id, { assignedTo: session.user.id }); if (assignment.status === 'ASSIGNED') assignment = await assignmentsApi.acceptAssignment(assignment.id); if (assignment.status === 'ACCEPTED') assignment = await assignmentsApi.startAssignment(assignment.id); if (assignment.status !== 'STARTED') throw new Error('Esta execução não está disponível para início.'); setExecutionAssignmentId(assignment.id); } else { setDetailOperationId(operation.id); setTick((value) => value + 1); } } catch (cause) { setError(cause instanceof ApiClientError || cause instanceof Error ? cause.message : 'Não foi possível preparar a execução.'); } finally { setBusyId(null); } }
  async function download(executionId: string, documentId: string) { setBusyId(executionId); setError(null); try { const file = await documentsApi.downloadDocument(documentId); const url = URL.createObjectURL(file.blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = file.filename ?? `relatorio-visita-tecnica-${executionId}.pdf`; document.body.appendChild(anchor); anchor.click(); anchor.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1_000); } catch (cause) { setError(cause instanceof ApiClientError || cause instanceof Error ? cause.message : 'Não foi possível baixar o PDF desta execução.'); } finally { setBusyId(null); } }
  if (plan.loading && !plan.data) return <SkeletonList rows={7} />; if (plan.error || !plan.data) return <ErrorState error={plan.error ?? new Error('RVT não encontrado')} onRetry={plan.refetch} />;
  const item = plan.data;
  return <div className="space-y-6"><Link href="/rvt" className="inline-flex items-center gap-2 text-sm text-[var(--color-primary)]"><ArrowLeft className="h-4 w-4" /> Voltar para RVTs</Link><PageHeader eyebrow={`RVT-${String(item.number).padStart(5, '0')}`} title={item.name} description={`${item.customer.tradeName ?? item.customer.name} · ${item.maintenanceType === 'WEEKLY' ? 'Semanal' : 'Semestral'}`} actions={canEdit && <button className={secondary} onClick={() => setEdit(true)}><Pencil className="h-4 w-4" /> Editar</button>} />
    {error && <ErrorState error={new Error(error)} onRetry={() => setError(null)} />}
    <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Info icon={CalendarDays} label="Cobertura" value={`${date(item.startDate)} a ${date(item.endDate)}`} /><Info icon={Wrench} label="Equipamentos" value={`${item.equipments.length} vinculado(s)`} /><Info icon={UserRound} label="Responsável técnico" value={item.responsibleTechnician.name} /><Info icon={FileText} label="Status" value={statusLabel(item.status)} /></div>
    <section className="rounded-xl border bg-[var(--color-card)] p-4"><h2 className="font-semibold">Equipamentos cobertos</h2><ul className="mt-3 grid gap-2 md:grid-cols-2">{item.equipments.map(({ equipment }) => <li key={equipment.id} className="rounded-lg bg-[var(--color-muted)] p-3 text-sm"><strong>{[equipment.manufacturer, equipment.model, equipment.capacity].filter(Boolean).join(' - ') || equipment.name}</strong><span className="block text-caption">{equipment.sector ?? 'Setor não informado'}</span></li>)}</ul></section>
    <section className="space-y-3"><div><h2 className="font-semibold">Execuções previstas</h2><p className="text-caption">Cada ocorrência gera um RVT independente somente depois da execução de campo.</p></div>{executions.loading && !executions.data ? <SkeletonList rows={5} /> : executions.error ? <ErrorState error={executions.error} onRetry={executions.refetch} /> : !executions.data?.items.length ? <EmptyState icon={CalendarDays} title="Nenhuma execução" description="Revise a cobertura desta configuração." /> : <><div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead className="bg-[var(--color-muted)] text-left"><tr><th className="p-3">Execução</th><th className="p-3">Prevista</th><th className="p-3">Operador</th><th className="p-3">Status</th><th className="p-3 text-right">Ação</th></tr></thead><tbody>{executions.data.items.map((execution) => { const readyDocument = execution.operation?.documents?.find((document) => document.type === 'TECHNICAL_REPORT' && document.status === 'READY'); return <tr key={execution.id} className="border-t"><td className="p-3 font-medium">#{String(execution.executionNumber).padStart(3, '0')}</td><td className="p-3">{date(execution.scheduledAt)}</td><td className="p-3">{execution.assignedOperator?.name ?? item.defaultOperator?.name ?? 'A definir'}</td><td className="p-3"><StatusChip tone={executionTone(execution.status)}>{executionLabel(execution.status)}</StatusChip></td><td className="p-3"><div className="flex justify-end gap-2">{execution.operationId ? <><button className={iconButton} type="button" disabled={busyId === execution.id} onClick={() => void prepare(execution.id)} title="Abrir detalhes e gerenciar atribuição"><FileText className="h-4 w-4" /></button>{canEdit && execution.status !== 'COMPLETED' && execution.status !== 'CANCELED' && <button className={iconButton} disabled={busyId === execution.id} onClick={() => void prepare(execution.id, true)} title="Executar RVT agora"><Play className="h-4 w-4" /></button>}{readyDocument && <button className={iconButton} type="button" disabled={busyId === execution.id} onClick={() => void download(execution.id, readyDocument.id)} title="Baixar PDF do RVT"><Download className="h-4 w-4" /></button>}</> : canEdit && execution.status !== 'CANCELED' ? <><button className={iconButton} disabled={busyId === execution.id} onClick={() => void prepare(execution.id)} title="Preparar e gerenciar atribuição"><UserPlus className="h-4 w-4" /></button><button className={iconButton} disabled={busyId === execution.id} onClick={() => void prepare(execution.id, true)} title="Executar RVT agora"><Play className="h-4 w-4" /></button></> : '—'}</div></td></tr>; })}</tbody></table></div><Pagination pagination={executions.data.pagination} onPageChange={setPage} onPageSizeChange={(value) => { setLimit(value); setPage(1); }} /></>}</section>
    <RvtPlanWizard open={edit} plan={item} onClose={() => setEdit(false)} onSaved={() => setTick((value) => value + 1)} />
    <OperationDetailDrawer operationId={detailOperationId} open={detailOperationId !== null} assignmentActionLabel="Confirmar atribuição" onClose={() => { setDetailOperationId(null); setTick((value) => value + 1); }} />
    <RvtExecutionDrawer assignmentId={executionAssignmentId} onClose={() => setExecutionAssignmentId(null)} onCompleted={() => setTick((value) => value + 1)} />
  </div>;
}
function Info({ icon: Icon, label, value }: { icon: typeof CalendarDays; label: string; value: string }) { return <div className="rounded-xl border bg-[var(--color-card)] p-4"><Icon className="h-5 w-5 text-[var(--color-primary)]" /><span className="mt-3 block text-caption">{label}</span><strong className="text-sm">{value}</strong></div>; }
function date(value: string) { return new Intl.DateTimeFormat('pt-BR', { timeZone: 'UTC' }).format(new Date(value)); }
function statusLabel(value: string) { return ({ ACTIVE: 'Ativo', PAUSED: 'Pausado', COMPLETED: 'Concluído', CANCELED: 'Cancelado' } as Record<string, string>)[value] ?? value; }
function executionLabel(value: RvtExecutionStatus) { return ({ PENDING: 'Pendente', ASSIGNED: 'Atribuída', IN_PROGRESS: 'Em andamento', COMPLETED: 'Concluída', CANCELED: 'Cancelada' } as const)[value]; }
function executionTone(value: RvtExecutionStatus): 'success' | 'warning' | 'info' | 'danger' { return value === 'COMPLETED' ? 'success' : value === 'CANCELED' ? 'danger' : value === 'PENDING' ? 'warning' : 'info'; }
const secondary = 'inline-flex h-10 items-center gap-2 rounded-md border px-4 text-sm font-medium'; const iconButton = 'inline-grid h-9 w-9 place-items-center rounded-md border hover:bg-[var(--color-muted)] disabled:opacity-50';
